FROM ubuntu:xenial

LABEL maintainer="devops@onix-systems.com"

RUN apt-get update && \
    apt-get install -y \
      libcurl4-openssl-dev \
      libmysqlclient-dev \
      libssl-dev \
      python-pip && \
    pip install \
      simplemysql \
      pycurl==7.43.0.3 \
      pyzabbix && \
    apt-get clean

CMD /bin/bash
